wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1631182318
    t:
      3:
      - 2
      4: 3.8.3
      5: 0.12.1
      8:
      - 3
      - 5
components:
  desc: null
  value:
    textcat:
      factory: textcat
      model:
        '@architectures': spacy.TextCatBOW.v2
        exclusive_classes: true
        ngram_size: 1
        'no': null
        no_output_layer: false
      threshold: 0.5
    tok2vec:
      factory: tok2vec
      model:
        '@architectures': spacy.Tok2Vec.v2
        embed:
          '@architectures': spacy.MultiHashEmbed.v2
          attrs:
          - ORTH
          - SHAPE
          include_static_vectors: false
          rows:
          - 5000
          - 2500
          width: 96
        encode:
          '@architectures': spacy.MaxoutWindowEncoder.v2
          depth: 4
          maxout_pieces: 3
          width: 96
          window_size: 1
corpora:
  desc: null
  value:
    dev:
      '@readers': spacy.Corpus.v1
      augmenter: null
      gold_preproc: false
      limit: 0
      max_length: 0
      path: corpus/dev.spacy
    train:
      '@readers': spacy.Corpus.v1
      augmenter: null
      gold_preproc: false
      limit: 0
      max_length: 0
      path: corpus/train.spacy
initialize:
  desc: null
  value:
    after_init: null
    before_init: null
    init_tok2vec: null
    lookups: null
    vectors: C:/Users/astelzl/Miniconda3/Lib/site-packages/en_core_web_md/en_core_web_md-3.1.0
    vocab_data: null
nlp:
  desc: null
  value:
    after_creation: null
    after_pipeline_creation: null
    batch_size: 1000
    before_creation: null
    disabled: []
    lang: en
    pipeline:
    - tok2vec
    - textcat
    tokenizer:
      '@tokenizers': spacy.Tokenizer.v1
paths:
  desc: null
  value:
    dev: corpus/dev.spacy
    init_tok2vec: null
    train: corpus/train.spacy
    vectors: C:/Users/astelzl/Miniconda3/Lib/site-packages/en_core_web_md/en_core_web_md-3.1.0
system:
  desc: null
  value:
    gpu_allocator: null
    seed: 0
training:
  desc: null
  value:
    accumulate_gradient: 1
    annotating_components: []
    batcher:
      '@batchers': spacy.batch_by_words.v1
      discard_oversize: false
      get_length: null
      size:
        '@schedules': compounding.v1
        compound: 1.001
        start: 100
        stop: 1000
        t: 0.0
      tolerance: 0.2
    before_to_disk: null
    dev_corpus: corpora.dev
    dropout: 0.1
    eval_frequency: 200
    frozen_components: []
    gpu_allocator: null
    logger:
      '@loggers': spacy.WandbLogger.v2
      log_dataset_dir: null
      model_log_interval: null
      project_name: UC02-textcat-loggingWandb
      remove_config_values: []
    max_epochs: 0
    max_steps: 20000
    optimizer:
      '@optimizers': Adam.v1
      beta1: 0.9
      beta2: 0.999
      eps: 1.0e-08
      grad_clip: 1.0
      l2: 0.01
      l2_is_weight_decay: true
      learn_rate: 0.001
      use_averages: false
    patience: 1600
    score_weights:
      cats_f_per_type: null
      cats_macro_auc: null
      cats_macro_auc_per_type: null
      cats_macro_f: null
      cats_macro_p: null
      cats_macro_r: null
      cats_micro_f: null
      cats_micro_p: null
      cats_micro_r: null
      cats_score: 1.0
      cats_score_desc: null
    seed: 0
    train_corpus: corpora.train
variables:
  desc: null
  value:
    wandb_project_name: UC02-textcat-loggingWandb
